[[plugins]]
repo= 'tpope/vim-surround'
on_event= 'InsertEnter'
[[plugins]]
repo = 'tpope/vim-commentary'
on_event = 'InsertEnter'
[[plugins]]
repo = 'tpope/vim-repeat'
on_event = 'InsertEnter'
[[plugins]]
repo = 'rhysd/clever-f.vim'
on_event = 'InsertEnter'
hook_add = '''
  let g:clever_f_use_migemo = 1
'''
# [[plugins]]
# repo = 'pepo-le/win-ime-con.nvim' #手動で ~/.cache/dein/repos/ にインストール
# on_event= 'InsertEnter'
# [[plugins]]
# repo = 'easymotion/vim-easymotion'
# on_event = 'VimEnter'
# hook_add = '''
#   let g:EasyMotion_do_mapping = 0
#   let g:EasyMotion_smartcase = 1
#   nmap <Leader>j <Plug>(easymotion-j)
#   nmap <Leader>k <Plug>(easymotion-k)
#   nmap s <Plug>(easymotion-s2)
#   nmap <Leader>w <Plug>(easymotion-bd-w)
# '''
[[plugins]]
repo= 'lervag/vimtex'
on_ft = 'tex'